server:
  port: 18888

spring:
  application:
    name: ts-assurance-service
  datasource:
    url: jdbc:mysql://ts-assurance-mysql:3306/ts-assurance-mysql?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

swagger:
  controllerPackage: assurance.controller