spring:
  application:
    name: ts-station-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ts-travel-mysql:3306/ts-route?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: fdsefdse
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# HTTP Server
server:
  port: 12345  # HTTP (Tomcat) port

swagger:
  controllerPackage: fdse.microservice