# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local
  application:
    name: ts-travel2-service
  data:
    mongodb:
      host: ts-travel2-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
swagger:
  controllerPackage: travel2.controller