# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  datasource:
    url: jdbc:mysql://ts-travel2-service:3306/ts-travel2-mysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver

  jpa:
    hibernate:
      ddl-auto: update

swagger:
  controllerPackage: travel2.controller