spring:
  application:
    name: ts-consign-price-service
  datasource:
    url: jdbc:mysql://ts-consign-price-mysql:3306/ts-consign-price-mysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


# HTTP Server
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller