spring:
  application:
    name: ts-consign-price-service
  data:
    mongodb:
      host: ts-consign-price-mongo
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16110
  ssl:
    key-store: classpath:keystore.p12
    keyStoreType: PKCS12
    keyAlias: tomcat
    key-store-password: ${KEY_STORE_PASSWORD}
http:
  client:
    ssl:
      key-store: classpath:keystore.p12
      trust-store: classpath:keystore.p12
      trust-store-password: ${KEY_STORE_PASSWORD}
swagger:
  controllerPackage: consignprice.controller