server:
  port: 12342

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-user-service
  data:
    mongodb:
      host: ts-user-mongo
      database: ts-user-mongo
      port: 27017

swagger:
  controllerPackage: user.controller