server:
  port: 12386

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-execute-service
swagger:
  controllerPackage: execute.controller