# HTTP Server
server:
  port: 12031  # HTTP (Tomcat) port


spring:
  application:
    name: ts-order-service
  datasource:
    url: jdbc:mysql://ts-order-mysql:3306/ts-order-mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://10.176.122.80:25765/ts-order-mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


swagger:
  controllerPackage: order.controller