server:
  port: 16114

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.176.122.80
  application:
    name: ts-admin-travel-service

swagger:
  controllerPackage: admintravel.controller