server:
  port: 16114

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-admin-travel-service

swagger:
  controllerPackage: admintravel.controller