spring:
  jpa:
    hibernate:
      ddl-auto: update
    application:
      name: ts-config-service
    datasource:
      url: jdbc:mysql://ts-config-mysql:3306/ts-config-mysql?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      #      url: jdbc:mysql://10.176.122.80:25997/ts-config-mysql?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#      jpa:
#        hibernate:
#          naming:
#            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#          ddl-auto: update
#        database-platform: org.hibernate.dialect.MySQL5Dialect

# HTTP Server
server:
  port: 15679  # HTTP (Tomcat) port

swagger:
  controllerPackage: config.controller