server:
  port: 16115

spring:
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: 5672
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller