server:
  port: 16115

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller