server:
  port: 18767

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.176.122.80
  application:
    name: ts-admin-basic-info-service

swagger:
  controllerPackage: adminbasic.microservice