server:
  port: 18767

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-admin-basic-info-service

swagger:
  controllerPackage: adminbasic.microservice