# HTTP Server
server:
  port: 19001  # HTTP (Tomcat) port
  ssl:
    key-store: classpath:keystore.p12
    keyStoreType: PKCS12
    keyAlias: tomcat
    key-store-password: ${KEY_STORE_PASSWORD}
http:
  client:
    ssl:
      key-store: classpath:keystore.p12
      trust-store: classpath:keystore.p12
      trust-store-password: ${KEY_STORE_PASSWORD}

spring:
  application:
    name: ts-payment-service
  data:
    mongodb:
      host: ts-payment-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: com.trainticket.controller