server:
  port: 15678  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-verification-code-service

swagger:
  controllerPackage: verifycode.controller