server:
  port: 18808

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-delivery-service
  data:
    mongodb:
      host: ${mongohost:ts-delivery-mongo}
      database: ts
      port: 27017
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}
