
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ts-train-service
  datasource:
    url: jdbc:mysql://ts-train-mysql:3306/ts-train-mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    url: jdbc:mysql://10.176.122.80:25996/ts-train-mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#    jpa:
#      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQL5Dialect





# HTTP Server
server:
  port: 14567  # HTTP (Tomcat) port

swagger:
  controllerPackage: train.controller