server:
  port: 12347

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-contacts-service
  data:
    mongodb:
      host: ts-contacts-mongo
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller