apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-inside-payment-service
spec:
  selector:
    matchLabels:
      app: ts-inside-payment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-inside-payment-service
    spec:
      containers:
        - name: ts-inside-payment-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-inside-payment-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.6:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.6"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
          ports:
            - containerPort: 18673
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 18673
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-payment-service
spec:
  selector:
    matchLabels:
      app: ts-payment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-payment-service
    spec:
      containers:
        - name: ts-payment-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-payment-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.6:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.6"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: KEY_STORE_PASSWORD
              value: "passw0rd"
          ports:
            - containerPort: 19001
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 19001
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
spec:
  ports:
    - name: http
      port: 18673
  selector:
    app: ts-inside-payment-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-payment-service
spec:
  ports:
    - name: http
      port: 19001
  selector:
    app: ts-payment-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-config-service
spec:
  selector:
    matchLabels:
      app: ts-config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-config-service
    spec:
      containers:
        - name: ts-config-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-config-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.6:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.6"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: KEY_STORE_PASSWORD
              value: "passw0rd"
          ports:
            - containerPort: 15679
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 15679
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
spec:
  ports:
    - name: http
      port: 15679
  selector:
    app: ts-config-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-price-service
spec:
  selector:
    matchLabels:
      app: ts-price-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-price-service
    spec:
      containers:
        - name: ts-price-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-price-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.6:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.6"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: KEY_STORE_PASSWORD
              value: "passw0rd"
          ports:
            - containerPort: 16579
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 16579
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
spec:
  ports:
    - name: http
      port: 16579
  selector:
    app: ts-price-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-admin-basic-info-service
spec:
  selector:
    matchLabels:
      app: ts-admin-basic-info-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-basic-info-service
    spec:
      containers:
        - name: ts-admin-basic-info-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-admin-basic-info-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.6:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.6"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
          ports:
            - containerPort: 18767
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 18767
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
spec:
  ports:
    - name: http
      port: 18767
  selector:
    app: ts-admin-basic-info-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-consign-price-service
spec:
  selector:
    matchLabels:
      app: ts-consign-price-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-price-service
    spec:
      containers:
        - name: ts-consign-price-service
          image: registry.cn-shanghai.aliyuncs.com/xywu/ts-consign-price-service:error.F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.6:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.6"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: KEY_STORE_PASSWORD
              value: "passw0rd"
          ports:
            - containerPort: 16110
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 16110
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-service
spec:
  ports:
    - name: http
      port: 16110
  selector:
    app: ts-consign-price-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-consign-service
spec:
  selector:
    matchLabels:
      app: ts-consign-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-service
    spec:
      containers:
        - name: ts-consign-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-consign-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
          ports:
            - containerPort: 16111
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 16111
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-service
spec:
  ports:
    - name: http
      port: 16111
  selector:
    app: ts-consign-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-food-map-service
spec:
  selector:
    matchLabels:
      app: ts-food-map-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-map-service
    spec:
      containers:
        - name: ts-food-map-service
          image: registry.cn-shanghai.aliyuncs.com/xywu/ts-food-map-service:error.F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.6:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.6"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: KEY_STORE_PASSWORD
              value: "passw0rd"
          ports:
            - containerPort: 18855
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 18855
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-map-service
spec:
  ports:
    - name: http
      port: 18855
  selector:
    app: ts-food-map-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-food-service
spec:
  selector:
    matchLabels:
      app: ts-food-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-service
    spec:
      containers:
        - name: ts-food-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-food-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: rabbitmq_host
              value: "rabbitmq"
            - name: rabbitmq_port
              value: "5672"
          ports:
            - containerPort: 18856
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 18856
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-service
spec:
  ports:
    - name: http
      port: 18856
  selector:
    app: ts-food-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-preserve-service
spec:
  selector:
    matchLabels:
      app: ts-preserve-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-preserve-service
    spec:
      containers:
        - name: ts-preserve-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-preserve-service:error-F4
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: rabbitmq_host
              value: "rabbitmq"
            - name: rabbitmq_port
              value: "5672"
          ports:
            - containerPort: 14568
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 14568
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-service
spec:
  ports:
    - name: http
      port: 14568
  selector:
    app: ts-preserve-service

---