server:
  port: 18898

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller