server:
  port: 19999

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:10.176.122.80:8848}
#        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-train-food-service
  datasource:
    url: jdbc:mysql://${TRAIN_FOOD_MYSQL_HOST:localhost}:${TRAIN_FOOD_MYSQL_PORT:3306}/${TRAIN_FOOD_MYSQL_DATABASE:ts-train-food-mysql}?useSSL=false
#    url: jdbc:mysql://${TRAIN_FOOD_MYSQL_HOST:ts-train-food-mysql}:${TRAIN_FOOD_MYSQL_PORT:3306}/${TRAIN_FOOD_MYSQL_DATABASE:ts-train-food-mysql}?useSSL=false
    username: ${TRAIN_FOOD_MYSQL_USER:root}
    password: ${ASSURANCE_MYSQL_PASSWORD:cqq2000929}
#    password: ${TRAIN_FOOD_MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: trainFood.controller