server:
  port: 15680

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-basic-service

swagger:
  controllerPackage: fdse.microservice.controller