server:
  port: 15680

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.176.122.80
  application:
    name: ts-basic-service

swagger:
  controllerPackage: fdse.microservice.controller