server:
  port: 16113

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.176.122.80
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller