server:
  port: 16113

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller