server:
  port: 18855

spring:
  application:
    name: ts-food-map-service
  data:
    mongodb:
      host: ts-food-map-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
  ssl:
    key-store: classpath:keystore.p12
    keyStoreType: PKCS12
    keyAlias: tomcat
    key-store-password: ${KEY_STORE_PASSWORD}
http:
  client:
    ssl:
      key-store: classpath:keystore.p12
      trust-store: classpath:keystore.p12
      trust-store-password: ${KEY_STORE_PASSWORD}
swagger:
  controllerPackage: food.controller