server:
  port: 18855

spring:
  application:
    name: ts-food-map-service
  datasource:
    url: jdbc:mysql://ts-food-map-mysql:3306/ts-food-map-mysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

swagger:
  controllerPackage: food.controller