server:
  port: 18856

spring:
  application:
    name: ts-food-service
  datasource:
    url: jdbc:mysql://ts-food-mysql:3306/ts-food-mysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
swagger:
  controllerPackage: foodsearch.controller