server:
  port: 18856

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.176.122.80
  application:
    name: ts-food-service
  data:
    mongodb:
      host: ts-food-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}
swagger:
  controllerPackage: foodsearch.controller