apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.rabbitmq.serverPort }}
      nodePort: 30555
    - name: http
      protocol: TCP
      port: 15672
      nodePort: 30556
  selector:
    app: {{ .Release.Name }}
