spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-security-service
  data:
    mongodb:
      host: ts-security-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 11188  # HTTP (Tomcat) port

swagger:
  controllerPackage: security.controller