spring:
  application:
    name: ts-security-service
  datasource:
    url: jdbc:mysql://ts-security-mysql:3306/ts-security-mysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#  data:
#    mongodb:
#      host: ts-security-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
#      database: ts
#      port: 27017

# HTTP Server
server:
  port: 11188  # HTTP (Tomcat) port

swagger:
  controllerPackage: security.controller