spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-security-service
  data:
    mongodb:
      host: ts-security-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 11188  # HTTP (Tomcat) port

swagger:
  controllerPackage: security.controller