#deploy cluster nacos
apiVersion: v1
kind: Service
metadata:
  name: nacos-server
  namespace: pie-engine-studio
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 30807
    - port: 7848
      name: rpc
      targetPort: 7848
  selector:
    app: nacos
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: pie-engine-studio
  labels:
    app: nacos-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 7848
      name: rpc
      targetPort: 7848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
  selector:
    app: nacos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: pie-engine-studio
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: "app"
#                    operator: In
#                    values:
#                      - nacos-headless
#              topologyKey: "kubernetes.io/hostname"
#      nodeSelector:
#        engine.node.studio: "true"
      containers:
        - name: k8snacos
          imagePullPolicy: IfNotPresent
          image:  nacos/nacos-server:1.3.1 #172.31.18.217:1110/pie-engine-common/nacos:1.4.2 nacos/nacos-server:1.4.0
          resources:
            requests:
              memory: "500Mi"
              cpu: "400m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 7848
              name: rpc
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              value: "10.176.122.77"
            - name: MYSQL_SERVICE_DB_NAME
              value: "nacos"
            - name: MYSQL_SERVICE_PORT
              value: "3306"
            - name: MYSQL_SERVICE_USER
              value: "root"
            - name: MYSQL_SERVICE_PASSWORD
              value: "123456"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.pie-engine-studio.svc.cluster.local:8848 nacos-1.nacos-headless.pie-engine-studio.svc.cluster.local:8848 nacos-2.nacos-headless.pie-engine-studio.svc.cluster.local:8848"
            - name: MODE
              value: "cluster"
  selector:
    matchLabels:
      app: nacos
