#和quickstart-ts-deployment-part4.yml配合测试nacos使用
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-verification-code-service
spec:
  selector:
    matchLabels:
      app: ts-verification-code-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-verification-code-service
    spec:
      containers:
        - name: ts-verification-code-service
          image: cqqcqq/ts-verification-code-service:0.2.1
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 15678
          envFrom:
            - configMapRef:
                name: config
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 15678
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  NACOS_SERVER_ADDR: nacos-0.nacos-headless.pie-engine-studio.svc.cluster.local,nacos-1.nacos-headless.pie-engine-studio.svc.cluster.local,nacos-2.nacos-headless.pie-engine-studio.svc.cluster.local