server:
  port: 12340
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.176.122.80
  application:
    name: ts-auth-service
  data:
    mongodb:
      host: ts-auth-mongo
      database: ts-auth-mongo
      port: 27017

swagger:
  controllerPackage: auth.controller