server:
  port: 16112

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-admin-order-service


swagger:
  controllerPackage: adminorder.controller