server:
  port: 16112

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.176.122.80
  application:
    name: ts-admin-order-service


swagger:
  controllerPackage: adminorder.controller