spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-consign-service
  data:
    mongodb:
      host: ts-consign-mongo
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16111

swagger:
  controllerPackage: consign.controller