# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port
  tomcat:
    max-threads: ${tomcat_maxthread}

spring:
  application:
    name: ts-ticketinfo-service


swagger:
  controllerPackage: ticketinfo.controller