---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-basic-service
spec:
  selector:
    matchLabels:
      app: ts-basic-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-basic-service
    spec:
      containers:
        - name: ts-basic-service
          image: registry.cn-shanghai.aliyuncs.com/xywu/ts-basic-service:error.F02-04
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
          ports:
            - containerPort: 15680
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 15680
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-seat-service
spec:
  selector:
    matchLabels:
      app: ts-seat-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-seat-service
    spec:
      containers:
        - name: ts-seat-service
          image: registry.cn-shanghai.aliyuncs.com/xywu/ts-seat-service:error.F02-04
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
          ports:
            - containerPort: 18898
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 18898
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5