apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-admin-basic-info-service
spec:
  selector:
    matchLabels:
      app: ts-admin-basic-info-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-basic-info-service
    spec:
      containers:
        - name: ts-admin-basic-info-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-admin-basic-info-service:error-F5
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: rest_template_timeout
              value: "30000"
          ports:
            - containerPort: 18767
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 18767
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
spec:
  ports:
    - name: http
      port: 18767
  selector:
    app: ts-admin-basic-info-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-config-service
spec:
  selector:
    matchLabels:
      app: ts-config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-config-service
    spec:
      containers:
        - name: ts-config-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-config-service:error-F5
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: sleep_seconds
              value: "10"
            - name: tomcat_maxthread
              value: "1"
          ports:
            - containerPort: 15679
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 15679
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
spec:
  ports:
    - name: http
      port: 15679
  selector:
    app: ts-config-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-price-service
spec:
  selector:
    matchLabels:
      app: ts-price-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-price-service
    spec:
      containers:
        - name: ts-price-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-price-service:sw1.6
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: sleep_seconds
              value: "10"
            - name: tomcat_maxthread
              value: "1"
          ports:
            - containerPort: 16579
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 16579
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
spec:
  ports:
    - name: http
      port: 16579
  selector:
    app: ts-price-service

---