apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-preserve-service
spec:
  selector:
    matchLabels:
      app: ts-preserve-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-preserve-service
    spec:
      containers:
        - name: ts-preserve-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-preserve-service:error-F1
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "172.19.109.144:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "172.19.109.144"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: rabbitmq_host
              value: "rabbitmq"
            - name: rabbitmq_port
              value: "5672"
          ports:
            - containerPort: 14568
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 14568
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-service
spec:
  ports:
    - name: http
      port: 14568
  selector:
    app: ts-preserve-service

---