apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-station-service
spec:
  selector:
    matchLabels:
      app: ts-station-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-station-service
    spec:
      containers:
        - name: ts-station-service
          image: registry.cn-hangzhou.aliyuncs.com/klouyge/fault-inject:f8.1-station-service
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.14:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.14"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
          ports:
            - containerPort: 12345
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 12345
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
spec:
  ports:
    - name: http
      port: 12345
  selector:
    app: ts-station-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
spec:
  ports:
    - name: http
      port: 12031
  selector:
    app: ts-order-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-order-service
spec:
  selector:
    matchLabels:
      app: ts-order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-service
    spec:
      containers:
        - name: ts-order-service
          image: registry.cn-hangzhou.aliyuncs.com/lavenpok/ts-order-service:error-F8
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "10.176.122.14:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "10.176.122.14"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
          ports:
            - containerPort: 12031
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 12031
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
---